name: rugo

services:
  app:
    container_name: rugo
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@rugo-db:${DB_PORT}/${DB_NAME}
      HOST_ADDRESS: 0.0.0.0
      HOST_PORT: 8080
    ports:
      - 8080:8080

  db:
    container_name: rugo-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - ./data:/var/lib/postgresql/data
