global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rugo"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rugo:8080"]
